version: '3.8'
services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: urlshortenerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge