spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortenerdb?currentSchema=public
    username: postgres
    password: pass
  data:
    redis:
      host: localhost
      port: 6379

url-shortener:
  base-url: http://localhost:8080/