spring:
  application:
    name: url-shortener
  profiles:
    active: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:urlshortenerdb}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

url-shortener:
  base-url: https://bit.any/
  short-code-size: 8

logging:
  level:
    root: info
    de:
      dkbcf:
        urlshortener: info